import { useEffect, useState, useRef } from 'react'
import { useNavigate } from 'react-router-dom'
import './ResultsPage.css'

/* ── Confidence Ring ── */
function ConfidenceRing({ value }) {
  const radius = 54
  const circumference = 2 * Math.PI * radius
  const offset = circumference * (1 - value)
  const pct = Math.round(value * 100)

  const color = value >= 0.9 ? '#52b788' : value >= 0.75 ? '#f4a261' : '#e63946'

  return (
    <div className="confidence-ring-wrap">
      <svg width="140" height="140" viewBox="0 0 140 140" className="confidence-ring-svg">
        {/* Track */}
        <circle
          cx="70" cy="70" r={radius}
          fill="none"
          stroke="rgba(255,255,255,0.05)"
          strokeWidth="10"
        />
        {/* Progress */}
        <circle
          cx="70" cy="70" r={radius}
          fill="none"
          stroke={color}
          strokeWidth="10"
          strokeLinecap="round"
          strokeDasharray={circumference}
          strokeDashoffset={offset}
          transform="rotate(-90 70 70)"
          className="confidence-ring-arc"
          style={{ filter: `drop-shadow(0 0 8px ${color})` }}
        />
      </svg>
      <div className="confidence-ring-center">
        <span className="confidence-ring-value" style={{ color }}>
          {pct}%
        </span>
        <span className="confidence-ring-label">Confidence</span>
      </div>
    </div>
  )
}

/* ── Top Predictions Bar ── */
function PredictionBars({ predictions }) {
  return (
    <div className="pred-bars">
      {predictions.map((p, i) => (
        <div key={i} className="pred-bar-item">
          <div className="pred-bar-header">
            <span className="pred-bar-name">{p.cls.label}</span>
            <span className="pred-bar-crop text-dim">({p.cls.crop})</span>
            <span className="pred-bar-pct">{(p.conf * 100).toFixed(1)}%</span>
          </div>
          <div className="progress-bar-wrap">
            <div
              className="progress-bar-fill"
              style={{
                width: `${p.conf * 100}%`,
                background: i === 0
                  ? 'linear-gradient(90deg, #2d6a4f, #52b788)'
                  : 'linear-gradient(90deg, rgba(82,183,136,0.3), rgba(82,183,136,0.5))',
                transition: `width ${0.5 + i * 0.1}s ease`,
              }}
            />
          </div>
        </div>
      ))}
    </div>
  )
}

export default function ResultsPage() {
  const navigate = useNavigate()
  const [result, setResult] = useState(null)
  const [imageUrl, setImageUrl] = useState(null)
  const [activeTab, setActiveTab] = useState('treatment')
  const [savedHistory, setSavedHistory] = useState(false)

  useEffect(() => {
    const raw = sessionStorage.getItem('agriAI_result')
    const img = sessionStorage.getItem('agriAI_imageUrl')

    if (!raw) {
      navigate('/detect')
      return
    }

    const data = JSON.parse(raw)
    setResult(data)
    if (img) setImageUrl(img)

    // Simulate saving to history
    setTimeout(() => setSavedHistory(true), 1500)
  }, [navigate])

  if (!result) return null

  const { primaryClass, confidence, severity, topPredictions, info } = result
  const isHealthy = primaryClass.isHealthy

  const severityMeta = {
    Low: { color: '#52b788', badge: 'badge-success', emoji: '🟢' },
    Moderate: { color: '#f4a261', badge: 'badge-warning', emoji: '🟡' },
    Severe: { color: '#e63946', badge: 'badge-danger', emoji: '🔴' },
  }
  const sev = severity ? severityMeta[severity] : null

  const handleDownload = () => {
    const report = `AgriAI Detection Report
========================
Date: ${new Date(result.timestamp).toLocaleString()}
Crop: ${primaryClass.crop}
Disease: ${isHealthy ? 'Healthy — No Disease Detected' : primaryClass.label}
Confidence: ${(confidence * 100).toFixed(1)}%
${severity ? `Severity: ${severity}` : ''}

${!isHealthy ? `Symptoms:
${info.symptoms.map(s => `• ${s}`).join('\n')}

Treatments:
${info.treatments.map(t => `• ${t}`).join('\n')}

Prevention:
${info.prevention.map(p => `• ${p}`).join('\n')}

Economic Impact:
${info.economicImpact}` : 'Your plant is healthy! Continue with regular monitoring and preventive practices.'}

---
Generated by AgriAI — AI-Powered Crop Disease Detection
`
    const blob = new Blob([report], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `AgriAI_Report_${primaryClass.crop}_${Date.now()}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="results-page">
      <div className="results-bg-glow" />

      <div className="container results-container">
        {/* Header Bar */}
        <div className="results-header animate-fadeInUp">
          <div>
            <span className="label">Detection Results</span>
            <h1 className="heading-md results-title">
              {isHealthy ? '✅ Plant is Healthy!' : `⚠️ Disease Detected: ${primaryClass.label}`}
            </h1>
            <p className="text-dim results-timestamp">
              Analyzed at {new Date(result.timestamp).toLocaleTimeString()} •
              <span style={{ color: savedHistory ? 'var(--color-primary)' : 'var(--color-text-3)' }}>
                {savedHistory ? ' ✓ Saved to history' : ' Saving...'}
              </span>
            </p>
          </div>
          <div className="results-header-actions">
            <button id="new-detect-btn" className="btn btn-outline" onClick={() => navigate('/detect')}>
              + New Detection
            </button>
            <button id="download-report-btn" className="btn btn-primary" onClick={handleDownload}>
              ⬇ Download Report
            </button>
          </div>
        </div>

        <div className="results-layout">
          {/* Left Column */}
          <div className="results-left">

            {/* Disease Card */}
            <div className={`results-disease-card ${isHealthy ? 'healthy' : 'diseased'} animate-fadeInUp delay-100`}>
              <div className="disease-card-img">
                {imageUrl ? (
                  <img src={imageUrl} alt="Analyzed leaf" className="disease-img" />
                ) : (
                  <div className="disease-img-placeholder">🌿</div>
                )}
                <div className="disease-card-overlay">
                  <div className="disease-overlay-badge">
                    <span className="disease-overlay-dot" style={{ background: isHealthy ? '#52b788' : '#e63946' }} />
                    <span>{isHealthy ? 'Healthy' : 'Disease Detected'}</span>
                  </div>
                </div>
              </div>

              <div className="disease-card-body">
                <div className="disease-card-info">
                  <div>
                    <div className="disease-crop-label text-dim">Crop</div>
                    <div className="disease-crop-val">{primaryClass.crop}</div>
                  </div>
                  <div>
                    <div className="disease-crop-label text-dim">Disease</div>
                    <div className="disease-crop-val">{isHealthy ? 'None' : primaryClass.label}</div>
                  </div>
                  {severity && (
                    <div>
                      <div className="disease-crop-label text-dim">Severity</div>
                      <span className={`badge ${sev.badge}`}>
                        {sev.emoji} {severity}
                      </span>
                    </div>
                  )}
                </div>
              </div>
            </div>

            {/* Confidence Ring */}
            <div className="confidence-card card animate-fadeInUp delay-200">
              <h3 className="heading-sm" style={{ marginBottom: '1rem' }}>Detection Confidence</h3>
              <ConfidenceRing value={confidence} />
              <p className="text-dim confidence-note">
                {confidence >= 0.9
                  ? 'Very high confidence — strong disease signal detected.'
                  : confidence >= 0.75
                  ? 'Good confidence — consider visual verification.'
                  : 'Moderate confidence — consult an agricultural expert.'}
              </p>
            </div>

            {/* Top Predictions */}
            <div className="predictions-card card animate-fadeInUp delay-300">
              <h3 className="heading-sm" style={{ marginBottom: '1rem' }}>Top Predictions</h3>
              <PredictionBars predictions={topPredictions.slice(0, 5)} />
            </div>
          </div>

          {/* Right Column — Info Panel */}
          <div className="results-right">
            {isHealthy ? (
              <div className="healthy-card card animate-fadeInUp delay-100">
                <div className="healthy-icon">🌿</div>
                <h2 className="heading-md" style={{ color: 'var(--color-primary)' }}>
                  Your Plant is Healthy!
                </h2>
                <p className="text-muted" style={{ lineHeight: 1.8 }}>
                  Great news! Our AI model found no signs of disease in your {primaryClass.crop} leaf.
                  Continue with regular monitoring to catch any early signs of disease.
                </p>
                <div className="healthy-tips">
                  {[
                    '🔍 Continue weekly scouting of your crop',
                    '💧 Maintain consistent irrigation and drainage',
                    '🌱 Apply preventive fungicide sprays during humid periods',
                    '✂️ Prune for good air circulation',
                    '📋 Keep records of plant health over time',
                  ].map(tip => (
                    <div key={tip} className="healthy-tip">{tip}</div>
                  ))}
                </div>
                <button
                  id="new-scan-btn"
                  className="btn btn-primary"
                  onClick={() => navigate('/detect')}
                  style={{ marginTop: '1rem' }}
                >
                  Scan Another Leaf
                </button>
              </div>
            ) : (
              <div className="disease-info-panel animate-fadeInUp delay-100">
                {/* Causes */}
                <div className="info-section card">
                  <h3 className="info-section-title">
                    <span className="info-section-icon">🔬</span>
                    Cause & Background
                  </h3>
                  <p className="text-muted" style={{ lineHeight: 1.8 }}>{info.causes}</p>
                  {info.economicImpact && (
                    <div className="economic-impact-note">
                      <span>💰</span>
                      <span className="text-dim">{info.economicImpact}</span>
                    </div>
                  )}
                </div>

                {/* Tabs */}
                <div className="info-tabs-card card" style={{ padding: 0, overflow: 'hidden' }}>
                  <div className="info-tabs">
                    {[
                      { key: 'symptoms', label: '🩺 Symptoms' },
                      { key: 'treatment', label: '💊 Treatment' },
                      { key: 'prevention', label: '🛡️ Prevention' },
                    ].map(tab => (
                      <button
                        key={tab.key}
                        id={`tab-${tab.key}`}
                        className={`info-tab ${activeTab === tab.key ? 'active' : ''}`}
                        onClick={() => setActiveTab(tab.key)}
                      >
                        {tab.label}
                      </button>
                    ))}
                  </div>

                  <div className="info-tab-content">
                    {activeTab === 'symptoms' && (
                      <ul className="info-list">
                        {info.symptoms.map(s => (
                          <li key={s} className="info-list-item">
                            <span className="info-list-bullet" />
                            {s}
                          </li>
                        ))}
                      </ul>
                    )}
                    {activeTab === 'treatment' && (
                      <ul className="info-list">
                        {info.treatments.map(t => (
                          <li key={t} className="info-list-item">
                            <span className="info-list-bullet treatment" />
                            {t}
                          </li>
                        ))}
                      </ul>
                    )}
                    {activeTab === 'prevention' && (
                      <ul className="info-list">
                        {info.prevention.map(p => (
                          <li key={p} className="info-list-item">
                            <span className="info-list-bullet prevention" />
                            {p}
                          </li>
                        ))}
                      </ul>
                    )}
                  </div>
                </div>

                {/* Urgency */}
                <div className={`urgency-card ${severity?.toLowerCase()}`}>
                  <div className="urgency-icon">
                    {severity === 'Severe' ? '🚨' : severity === 'Moderate' ? '⚠️' : 'ℹ️'}
                  </div>
                  <div>
                    <div className="urgency-title">
                      {severity === 'Severe'
                        ? 'Immediate Action Required'
                        : severity === 'Moderate'
                        ? 'Action Recommended Soon'
                        : 'Monitor & Treat When Convenient'}
                    </div>
                    <div className="urgency-desc text-dim">
                      {severity === 'Severe'
                        ? 'Apply treatment within 24-48 hours to prevent total crop loss.'
                        : severity === 'Moderate'
                        ? 'Apply treatment within the next week during dry conditions.'
                        : 'Address within 2–3 weeks; monitor spread closely.'}
                    </div>
                  </div>
                </div>

                {/* Treatment Marketplace / Recommended Products */}
                <div className="marketplace-section card animate-fadeInUp delay-200">
                  <h3 className="heading-sm" style={{ marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '8px' }}>
                    <span>🛒</span> Recommended Products
                  </h3>
                  <div className="marketplace-grid">
                    {[
                      { name: 'Copper Fungicide 32oz', price: '$14.99', type: 'Fungicide', img: '🧴' },
                      { name: 'Neem Oil Extract', price: '$22.50', type: 'Organic Spray', img: '🌿' },
                    ].map(prod => (
                      <div key={prod.name} className="marketplace-item">
                        <div className="marketplace-img">{prod.img}</div>
                        <div className="marketplace-info">
                          <div className="marketplace-name">{prod.name}</div>
                          <div className="marketplace-type text-dim">{prod.type}</div>
                          <div className="marketplace-price">{prod.price}</div>
                        </div>
                        <button className="btn btn-primary btn-sm">Buy Now</button>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Actions */}
                <div className="results-actions">
                  <button
                    id="results-detect-again-btn"
                    className="btn btn-outline"
                    onClick={() => navigate('/detect')}
                  >
                    Scan Another Leaf
                  </button>
                  <button
                    id="results-dashboard-btn"
                    className="btn btn-ghost"
                    onClick={() => navigate('/dashboard')}
                  >
                    View Dashboard
                  </button>
                  <button
                    id="results-download-btn-2"
                    className="btn btn-primary"
                    onClick={handleDownload}
                  >
                    ⬇ Download Report
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}
